dist: xenial

language: python

sudo: false

python:
  - 3.8
  - 3.7
  - 3.6

install:
  - pip install pytest coverage coveralls

script:
  - coverage run --source=deflacue setup.py test

after_success:
  - coveralls
